spring:
  data:
    cassandra:
      keyspace-name: test_ks
      schema-action: CREATE_IF_NOT_EXISTS
      contact-points: cassandra
      local-datacenter: datacenter1
      port: 9042
      create-keyspace: true
  kafka:
    template:
      default-topic: "follower"
    consumer:
      bootstrap-servers: 192.168.1.16:9092
      group-id: group_id
      auto-offset-reset: earliest
      properties.spring.json.trusted.packages: com.bezkoder.spring.data.cassandra.*
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      
    producer:
      bootstrap-servers: 192.168.1.16:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer